media_folder: /img/uploads
#public_folder: /img/uploads
display_url: https://komareus.github.io
backend:
#  name: github
  name: git-gateway
#  repo: komareus/komareus.github.io
  branch: master
  accept_roles: #optional - accepts all users if left out
      - admin
      - editor

#  site_domain: komareus.github.io
collections:
  - name: warnings
    label: Warnings
    folder: 'content/warnings'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: Active
        name: active
        widget: boolean
        default: true
      - label: Title
        name: title
        widget: string
        required: true
      - label: Publish date
        name: date
        widget: datetime
      - label: Content
        name: text
        widget: markdown
  - name: news
    label: News
    folder: 'content/news'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
        required: true
      - label: Publish date
        name: date
        widget: datetime
      - label: Short text
        name: short
        widget: text
        required: true
      - label: Content
        name: body
        widget: list
        allow_add: true
        fields:
          - {label: Paragraph, name: body, widget: markdown}
          - label: Images
            name: img
            widget: list
            allow_add: true
            fields:
              - {label: Image, name: src, widget: image}
  - name: documents_direction_statutory
    label: documents_direction_statutory
    folder: 'content/documents/directions/statutory'
    format: json
    create: true
    slug: '/{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}/index.json'
    media_folder: "/content/documents/directions/statutory/{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: File
        name: file
        widget: file
