media_library:
  name: cloudinary
#  output_filename_only: true
  config:
    cloud_name: investor182
    api_key: 525457938989435
    api_secret: mI3kOhd9tUJcFavZ45wPbxgmV7E
#media_folder: /img/uploads
#media_folder_relative: false
#public_folder: /img/uploads
display_url: https://cloudinary.com/users/login
backend:
#  name: github
  name: git-gateway
#  repo: komareus/komareus.github.io
  branch: master
  accept_roles: #optional - accepts all users if left out
      - admin
      - directors
      - revision
      - supervisory

#  site_domain: komareus.github.io
collections:
  - name: warnings
    label: 'ОГОЛОШЕННЯ'
    folder: 'content/warnings'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Активувати оголошення'
        name: active
        widget: boolean
        default: true
      - label: 'Назва оголошення'
        name: title
        widget: string
        required: true
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Текст оголошення'
        name: text
        widget: markdown
  - name: news
    label: 'НОВИНИ'
    folder: 'content/news'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва новини'
        name: title
        widget: string
        required: true
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис новини'
        name: short
        widget: text
        required: true
      - label: 'Текст новини'
        name: body
        widget: list
        allow_add: true
        fields:
          - {label: 'Новий розділ новини', name: body, widget: markdown}
          - label: 'Додати зображення'
            name: img
            widget: list
            allow_add: true
            fields:
              - label: 'Зображення'
                name: src
                widget: image
                media_library:
                  config:
                    default_transformations:
                      - width: 600
                        quality: auto
                        crop: fit
  - name: documents
    label: 'ДОКУМЕНТИ (різні)'
    folder: 'content/documents/other'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        fields:
          - label: 'Завантажити зображення'
            name: src
            widget: image
            required: false
            media_library:
              config:
                default_transformations:
                  - width: 600
                    quality: auto
                    crop: fit

#  - name: test
#    label:  TEST
#    files:
#      - label: "About Page"
#        name: "about"
#        file: "/content/test.json"
#        fields:
#          - {label: Title, name: title, widget: string}
#          - {label: Intro, name: intro, widget: markdown}
#          - label: Team
#            name: team
#            widget: list
#            fields:
#              - {label: Name, name: name, widget: string}
#              - {label: Position, name: position, widget: string}
#              - {label: Photo, name: photo, widget: image}

