media_library:
  name: cloudinary
#  output_filename_only: true
  config:
    cloud_name: supervisory182
    api_key: 389681379362281
#media_folder: /img/uploads
#media_folder_relative: false
#public_folder: /img/uploads
display_url: https://cloudinary.com/users/login
backend:
#  name: github
  name: git-gateway
#  repo: komareus/komareus.github.io
  branch: master
  accept_roles: #optional - accepts all users if left out
      - admin
      - supervisory

#  site_domain: komareus.github.io
collections:
  - name: documentsStatutory
    label: 'Протоколи'
    folder: 'content/documents/supervisory-protocols'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        fields:
          - label: 'Завантажити зображення'
            name: src
            widget: image
            required: false
            media_library:
              config:
                default_transformations:
                  - width: 600
                    quality: auto
                    crop: fit
  - name: documentsMail
    label: 'Інформаційні листи'
    folder: 'content/documents/supervisory-letters'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        fields:
          - label: 'Завантажити зображення'
            name: src
            widget: image
            required: false
            media_library:
              config:
                default_transformations:
                  - width: 600
                    quality: auto
                    crop: fit
  - name: documentsOther
    label: 'Документи різні'
    folder: 'content/documents/supervisory-other'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        fields:
          - label: 'Завантажити зображення'
            name: src
            widget: image
            required: false
            media_library:
              config:
                default_transformations:
                  - width: 600
                    quality: auto
                    crop: fit
