media_library:
  name: cloudinary
  config:
    cloud_name: directors182
    api_key: 199374639964265
display_url: https://cloudinary.com/users/login
backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
      - admin
      - directors
#  site_domain: komareus.github.io
collections:
  - name: documentsStatutory
    label: 'Документи статутні'
    folder: 'content/documents/directors-statutory'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        field:
          label: 'Завантажити зображення'
          name: src
          widget: image
          required: false
          media_library:
            config:
              default_transformations:
                - width: 600
                  quality: auto
                  crop: fit

  - name: documentsAgreements
    label: 'Договори'
    folder: 'content/documents/directors-agreements'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        field:
          label: 'Завантажити зображення'
          name: src
          widget: image
          required: false
          media_library:
            config:
              default_transformations:
                - width: 600
                  quality: auto
                  crop: fit
  - name: documentsMail
    label: 'Листування'
    folder: 'content/documents/directors-letters'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        field:
          label: 'Завантажити зображення'
          name: src
          widget: image
          required: false
          media_library:
            config:
              default_transformations:
                - width: 600
                  quality: auto
                  crop: fit
  - name: documentsProtocols
    label: 'Протоколи'
    folder: 'content/documents/directors-protocols'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        field:
          label: 'Завантажити зображення'
          name: src
          widget: image
          required: false
          media_library:
            config:
              default_transformations:
                - width: 600
                  quality: auto
                  crop: fit
  - name: documentsOther
    label: 'Документи різні'
    folder: 'content/documents/directors-other'
    format: json
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{slug}}'
    fields:
      - label: 'Назва документа'
        name: title
        widget: string
      - label: 'Дата публікування'
        name: date
        widget: datetime
      - label: 'Короткий опис'
        name: description
        widget: text
        required: false
      - label: 'Завантажити файл документа'
        name: file
        widget: file
        required: false
      - label: 'Додати посилання на документ'
        name: link
        widget: string
        required: false
      - label: 'Завантажити фото/скани документа'
        name: img
        widget: list
        allow_add: true
        required: false
        field:
          label: 'Завантажити зображення'
          name: src
          widget: image
          required: false
          media_library:
            config:
              default_transformations:
                - width: 600
                  quality: auto
                  crop: fit
